### ISSUE TITLE
Requirements for `transformers` incorrect

### ISSUE THREAD

**Issue by wrosko** [INK-USC/MHGRN#1]
According to the environment creation that is outlined, `transformers==2.0.0`. If this is done, then any of the models containing the line 
```
from transformers import (OPENAI_GPT_PRETRAINED_CONFIG_ARCHIVE_MAP, 
                          BERT_PRETRAINED_CONFIG_ARCHIVE_MAP, 
                          XLNET_PRETRAINED_CONFIG_ARCHIVE_MAP,
                          ROBERTA_PRETRAINED_CONFIG_ARCHIVE_MAP,
                          ALBERT_PRETRAINED_MODEL_ARCHIVE_MAP)
```
will fail upon trying to import `ALBERT_PRETRAINED_MODEL_ARCHIVE_MAP` because it wasn't implemented in `transformers` until at least `transformers==2.2.0`

It appears that `2.2.0` makes it past the import, but I'm curious if you know whether this will impact your models and which versions of transformers will work.

**Comment by wrosko** [comment]
Additionally updating the example conda environment creation for the required pytorch version would be useful.

**Comment by Kiwisher** [comment]
> Additionally updating the example conda environment creation for the required pytorch version would be useful.

Thanks for pointing out! We have updated the requirements in the readme file.
