### ISSUE TITLE
resource missing

### ISSUE THREAD

**Issue by chenchonghao** [INK-USC/MHGRN#16]
Can you provide the resource of pretrained TransE embeddings and  BERT features？ The original links are invalid.

**Comment by yuchenlin** [comment]
Hi can you download the files from here for now? https://drive.google.com/drive/folders/155codqEnsKazO8-BchF3rO_cP3EyYdws

We will update the links later. Thanks!

**Comment by caiqizh** [comment]
Thanks for the link! But the train.bert.large.layer-2.epoch1.npy and dev.bert.large.layer-2.epoch1.npy are still missing.
