### ISSUE TITLE
Not able to run kagnet or grn 

### ISSUE THREAD

**Issue by akshayg08** [INK-USC/MHGRN#9]
I have followed all the steps. Ran the preprocess.py too. But, I am not able train kagnet or grn, I am getting the following error.
"FileNotFoundError: [Errno 2] No such file or directory: './data/cpnet/tzw.ent.npy'". Can someone please help me to train kagnet.

**Comment by yuchenlin** [comment]
https://github.com/INK-USC/MHGRN#entity-embeddings-node-features check this table and you can download it here.
